#%RAML 1.0 ImagePair
description: Pair of original and modified images
post:
  description: Create a new image-pair with new differences
  body:
    multipart/form-data:
      properties: 
        name: string
        originalImage:
          type: file
          fileTypes: ['image/bmp']
        modifiedImage:
          type: file
          fileTypes: ['image/bmp']
  responses:
    200:
      description: The image pair was created successfully
      body:
        application/json:
          example: |
            {
              "id":"438943af323ed43",
              "url_difference":"http://localhost:3000/image-pair/438943af323ed43/difference",
              "url_modified":"http://localhost:3000/image-pair/438943af323ed43/modified",
              "url_original":"http://localhost:3000/image-pair/438943af323ed43/original",
              "name":"The name of the pair",
              "creation_date":"2019-01-27T19:50:48.036Z",
              "differences_count":7
            }
    400:
      description: "There is an error with the request"
      body:
        application/json:
          example: |
            {
              "title":"Error",
              "body":"The field originalImage is not present in the request"
            }
/{id}:
  get:
    description: Returns a bunch of informations about the pair
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id":"438943af323ed43",
                "url_differences":"http://localhost:3000/image-pair/438943af323ed43/difference",
                "url_modified":"http://localhost:3000/image-pair/438943af323ed43/modified",
                "url_original":"http://localhost:3000/image-pair/438943af323ed43/original",
                "name":"The name of the pair",
                "creation_date":"2019-01-27T19:50:48.036Z",
                "differences_count":7
              }
      404:
        body:
          application/json:
            example: |
              {
                "title":"Error",
                "body": "The pair could not be found"
              }
  /difference:
    get:
      description: Returns the bmp file with the differences highlighted
  /difference.json:
    get:
      description: Returns an array of number representing every pixels with their difference id.
  /modified:
    get:
      description: Returns the bmp file of the modified image
  /original:
    get:
      description: Returns the bmp file of the original image
  
