#%RAML 1.0
title: Spot the differences API
baseUri: http://localhost:3000
version: 1
/user:
  description: Manages the user on the server
  post:
    description: Create a new user on the server
    body:
      multipart/form-data:
        properties: 
          username: string
    responses: 
      200:
        description: The user was created successfully
        body:
          application/json:
            example: |
              {
                "id":"438943af323ed43",
                "username":"my user",
                "creation_date":"2019-02-02 08:11:33.001Z"
              }
      409:
        description: There is already a user with the same username on the server
        body:
          application/json:
            example: |
              {
                "title":"Error",
                "body":"There is already a user with the same username on the server"
              }
  get:
    description: Return a list of all the users on the server
    responses: 
      200:
        description: Returns a list of all users
        body:
          application/json:
            example: |
              [
                {
                  "id":"438943af323ed43",
                  "username":"my user",
                  "creation_date":"2019-02-02 08:11:33.001Z"
                }
              ]
  /{id}:
    delete:
      description: Delete the user from a server
      responses: 
        200:
          description: Deletes the user from the server
          body:
            application/json:
              example: |
                {
                  "title":"Success",
                  "body":"The user was deleted"
                }
        404:
          description: The user could not be found
          body:
            application/json:
              example: |
                {
                  "title":"Error",
                  "body":"The user could not be found"
                }
    get:
      description: Returns the information about the user
      responses: 
        200:
          description: The user and its data
          body:
            application/json:
              example: |
                {
                  "id":"438943af323ed43",
                  "username":"my user",
                  "creation_date":"2019-02-02 08:11:33.001Z"
                }
        404:
          description: The user could not be found
          body:
            application/json:
              example: |
                {
                  "title":"Error",
                  "body":"The user could not be found"
                }
/image-pair:
  description: Pair of original and modified images
  post:
    description: Create a new image-pair with new differences
    body:
      multipart/form-data:
        properties: 
          name: string
          originalImage:
            type: file
            fileTypes: ['image/bmp']
          modifiedImage:
            type: file
            fileTypes: ['image/bmp']
    responses:
      200:
        description: The image pair was created successfully
        body:
          application/json:
            example: |
              {
                "id":"438943af323ed43",
                "url_difference":"http://localhost:3000/image-pair/438943af323ed43/difference",
                "url_modified":"http://localhost:3000/image-pair/438943af323ed43/modified",
                "url_original":"http://localhost:3000/image-pair/438943af323ed43/original",
                "name":"The name of the pair",
                "creation_date":"2019-01-27T19:50:48.036Z",
                "differences_count":7
              }
      400:
        description: "There is an error with the request"
        body:
          application/json:
            example: |
              {
                "title":"Error",
                "body":"The field originalImage is not present in the request"
              }
  /{id}:
    get:
      description: Returns a bunch of informations about the pair
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id":"438943af323ed43",
                  "url_differences":"http://localhost:3000/image-pair/438943af323ed43/difference",
                  "url_modified":"http://localhost:3000/image-pair/438943af323ed43/modified",
                  "url_original":"http://localhost:3000/image-pair/438943af323ed43/original",
                  "name":"The name of the pair",
                  "creation_date":"2019-01-27T19:50:48.036Z",
                  "differences_count":7
                }
        404:
          body:
            application/json:
              example: |
                {
                  "title":"Error",
                  "body": "The pair could not be found"
                }
    /difference:
      get:
        description: Returns the bmp file with the differences highlighted
    /modified:
      get:
        description: Returns the bmp file of the modified image
    /original:
      get:
        description: Returns the bmp file of the original image
    
/gamecard:
  post:
    description: Create a new gamecard
    body:
      multipart/form-data:
        properties: 
          name: string
          image-pair-id: string
          pov:
            type: string
            enum: [Simple, Free]
    responses:
      200:
        body:
          application/json:
            example: |
              {
              "id":"432423423423ef",
              "pov":"Simple",
              "title":"The name of the gamecard",
              "image_pair":
                {
                "id":"438943af323ed43",
                "url_differences":"http://localhost:3000/image-pair/438943af323ed43/difference",
                "url_modified":"http://localhost:3000/image-pair/438943af323ed43/modified",
                "url_original":"http://localhost:3000/image-pair/438943af323ed43/original",
                "name":"The name of the pair",
                "creation_date":"2019-01-27T19:50:48.036Z",
                "differences_count":7
                },
              "best_time_solo":[1254512,1282445,544512],
              "best_time_online":[1254512,1282445,544512]
              }
      400:
        body:
          application/json:
            example: |
              {
                "title":"Error",
                "body":"The pov is not a Simple or free type"
              }
  get:
    description: Retrieve all the gamecards
    responses: 
          200:
            body: 
              application/json:
                example: |
                  [
                    {
                      "id":"432423423423ef",
                      "pov":"Simple",
                      "title":"The name of the gamecard",
                      "image_pair":
                        {
                        "id":"438943af323ed43",
                        "url_differences":"http://localhost:3000/image-pair/438943af323ed43/difference",
                        "url_modified":"http://localhost:3000/image-pair/438943af323ed43/modified",
                        "url_original":"http://localhost:3000/image-pair/438943af323ed43/original",
                        "name":"The name of the pair",
                        "creation_date":"2019-01-27T19:50:48.036Z",
                        "differences_count":7
                        },
                      "best_time_solo":[1254512,1282445,544512],
                      "best_time_online":[1254512,1282445,544512]
                    }
                  ]
  /{id}:
    get:
      description: Retrieve data about a gamecard
      responses: 
        200:
          body:
            application/json:
              example: |
                {
                "id":"432423423423ef",
                "pov":"Simple",
                "title":"The name of the gamecard",
                "image_pair":
                  {
                  "id":"438943af323ed43",
                  "url_differences":"http://localhost:3000/image-pair/438943af323ed43/difference",
                  "url_modified":"http://localhost:3000/image-pair/438943af323ed43/modified",
                  "url_original":"http://localhost:3000/image-pair/438943af323ed43/original",
                  "name":"The name of the pair",
                  "creation_date":"2019-01-27T19:50:48.036Z",
                  "differences_count":7
                  },
                "best_time_solo":[1254512,1282445,544512],
                "best_time_online":[1254512,1282445,544512]
                }
    delete:
      description: Delete a gamecard
      responses:
        200:
          body:
            application/json:
              example: |
                {
                "title":"success",
                "body":"Gamecard was deleted successfully"
                }
