#%RAML 1.0
title: Spot the differences API
baseUri: http://localhost:3000
version: 1
/user: !include request/user.raml
/image-pair: !include request/image-pair.raml
/gamecard: !include request/gamecard.raml
/scene: !include request/scene.raml
/difference: !include request/difference.raml